name: appinio_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  decimal: ^2.3.3
  equatable: ^2.0.5
  firebase_core: ^2.24.2

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  url_launcher: ^6.2.4

dev_dependencies:
  alchemist: ^0.7.0
  architecture_lints:
    path: tools/custom_lints/architecture_lints

  custom_lint: ^0.5.11

  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.15.0
  meta: ^1.10.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
