name: architecture_lints
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.11
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  very_good_analysis: ^5.1.0
