// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIgRd4jfKMvQLBO4Wf-_3jAcffqI20CzA',
    appId: '1:828552165099:web:5c5c9cc726f636a3f7f0ae',
    messagingSenderId: '828552165099',
    projectId: 'appinio-home-work',
    authDomain: 'appinio-home-work.firebaseapp.com',
    storageBucket: 'appinio-home-work.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZ8LOO-plxtvxVBa7F5E9UPgTWybMlKQ',
    appId: '1:828552165099:android:f679f75a3c8dce33f7f0ae',
    messagingSenderId: '828552165099',
    projectId: 'appinio-home-work',
    storageBucket: 'appinio-home-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DiZc_qaLTCq64siU-jSuhY9qQqv-rY0',
    appId: '1:828552165099:ios:28fabcb68254f3eff7f0ae',
    messagingSenderId: '828552165099',
    projectId: 'appinio-home-work',
    storageBucket: 'appinio-home-work.appspot.com',
    iosBundleId: 'com.example.appinioBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2DiZc_qaLTCq64siU-jSuhY9qQqv-rY0',
    appId: '1:828552165099:ios:7a5d8332262d0065f7f0ae',
    messagingSenderId: '828552165099',
    projectId: 'appinio-home-work',
    storageBucket: 'appinio-home-work.appspot.com',
    iosBundleId: 'com.example.appinioBloc.RunnerTests',
  );
}
