name: Appinio Home Test CI/CD

on:
  workflow_dispatch:
  push:
    branches: [cicd]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build apk --build-number ${{ github.run_number }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: ${{ github.run_number }}
          name: "Release #${{ github.run_number }}"

  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --base-href '/appinio-home-test/'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/web