name: Appinio Home Test CI/CD

on:
  workflow_dispatch:
  push:
    branches: [cicd]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --base-href '/appinio-home-test/'
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ./build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: web-build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-build